# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 155530c7b39c2793de69cfac306184cd3055c648c3d5aae760a937b4d67c5845e428f30d22cf64d8162ac5eb15f67abad7e0c849fdd2f4bedcd5056647ab81a6

test:
  secret_key_base: 57608b759bdfda16306f6bdd38c8eea6077f6795c1b0bc8d863af4caab894f9f9e4bc484f0ef708221e2c19f57b79bd14fb08c8a0d2d471d93d4ac3910c3786c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
